url: https://mhudasch.github.io
baseurl: /unable-to-get-local-issuer-certificate
theme: al-folio
title: unable to get local issuer certificate
description: Helping with one of the banes of development