# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: unable to get local issuer certificate # the website title (if blank, full name will be used instead)
first_name: Martin
#middle_name: R.
last_name: Hudasch
email: martin.hudasch@live.de
description: > # the ">" symbol means to ignore newlines until "footer_text:"
  Helping with one of the banes of development
footer_text: >
  Made with ❤️ by Martin Hudasch
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
keywords: certificate, unable, issuer, ruby, dotnet, nuget, msys, pip, python  # add your own keywords or leave empty

lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: ⚛️  # the emoji used as the favicon (alternatively, provide image name in /assets/img/)

url: https://mhudasch.github.io # the base hostname & protocol for your site
baseurl: /unable-to-get-local-issuer-certificate # the subpath of your site, e.g. /blog/
last_updated: false # set to true if you want to display last updated in the footer
impressum_path:  # set to path to include impressum link in the footer, use the same path as permalink in a page, helps to conform with EU GDPR
github_username: mhudasch

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------
theme: documentation